
links:
- href: https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-beta/css/bootstrap-reboot.min.css
  integrity: sha256-ZeIRHNBrNlXFlcfvaKsx9S1BOwWJ42hBund78iurMLw=

- href: https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css
  integrity: sha384-zhIsEafzyQWHSoMCQ4BfT8ZlRXQyIFwAHAJn32PNdsb8n6tVysGZSLpEEIvCskw4

- href: tko.css

scripts:
- src: https://unpkg.com/tko@4.0.0-alpha3/dist/ko.js
  integrity: sha256-F8J/QUq35S+E/Ri8ahVGQxime/L5PCeXEmHTvkh1MV8=
  crossorigin: anonymous

- src: https://production-assets.codepen.io/assets/embed/ei.js

- src: tko-io.js
  type: module

dest: build/index.html
sources:
- ../packages/tko/docs/intro.md
- ../packages/tko.bind/docs/binding-context.md

 # - ../packages/tko.bind/docs/binding-preprocessing.md
 # - ../packages/tko.bind/docs/binding-syntax.md
 # - ../packages/tko.bind/docs/custom-bindings-controlling-descendant-bindings.md
 # - ../packages/tko.bind/docs/custom-bindings-disposal.md
 # - ../packages/tko.bind/docs/custom-bindings-for-virtual-elements.md
 # - ../packages/tko.bind/docs/custom-bindings.md
 # - ../packages/tko.binding.core/docs/attr-binding.md
 # - ../packages/tko.binding.core/docs/checked-binding.md
 # - ../packages/tko.binding.core/docs/click-binding.md
 # - ../packages/tko.binding.core/docs/css-binding.md
 # - ../packages/tko.binding.core/docs/disable-binding.md
 # - ../packages/tko.binding.core/docs/enable-binding.md
 # - ../packages/tko.binding.core/docs/event-binding.md
 # - ../packages/tko.binding.core/docs/hasfocus-binding.md
 # - ../packages/tko.binding.core/docs/html-binding.md
 # - ../packages/tko.binding.core/docs/options-binding.md
 # - ../packages/tko.binding.core/docs/selectedOptions-binding.md
 # - ../packages/tko.binding.core/docs/style-binding.md
 # - ../packages/tko.binding.core/docs/submit-binding.md
 # - ../packages/tko.binding.core/docs/text-binding.md
 # - ../packages/tko.binding.core/docs/textInput-binding.md
 # - ../packages/tko.binding.core/docs/uniqueName-binding.md
 # - ../packages/tko.binding.core/docs/unobtrusive-event-handling.md
 # - ../packages/tko.binding.core/docs/value-binding.md
 # - ../packages/tko.binding.core/docs/visible-binding.md
 # - ../packages/tko.binding.if/docs/if-binding.md
 # - ../packages/tko.binding.if/docs/ifnot-binding.md
 # - ../packages/tko.binding.if/docs/index.md
 # - ../packages/tko.binding.if/docs/with-binding.md
 # - ../packages/tko.binding.template/docs/foreach-binding.md
 # - ../packages/tko.binding.template/docs/template-binding.md
 # - ../packages/tko.computed/docs/computed-dependency-tracking.md
 # - ../packages/tko.computed/docs/computed-pure.md
 # - ../packages/tko.computed/docs/computed-reference.md
 # - ../packages/tko.computed/docs/computed-writable.md
 # - ../packages/tko.computed/docs/computedObservables.md
 # - ../packages/tko.lifecycle/docs/life-cycle.md
 # - ../packages/tko.observable/docs/arraychange.md
 # - ../packages/tko.observable/docs/extenders.md
 # - ../packages/tko.observable/docs/observableArrays.md
 # - ../packages/tko.observable/docs/observables.md
 # - ../packages/tko.observable/docs/rateLimit-observable.md
 # - ../packages/tko.observable/docs/throttle-extender.md
 # - ../packages/tko.provider.databind/docs/databind-parser.md
 # - ../packages/tko.provider/docs/provider.md
 # - ../packages/tko.utils.component/docs/component-binding.md
 # - ../packages/tko.utils.component/docs/component-custom-elements.md
 # - ../packages/tko.utils.component/docs/component-loaders.md
 # - ../packages/tko.utils.component/docs/component-overview.md
 # - ../packages/tko.utils.component/docs/component-registration.md
 # - ../packages/tko/docs/amd-loading.md
 # - ../packages/tko/docs/animated.md
 # - ../packages/tko/docs/api.md
 # - ../packages/tko/docs/books.md
 # - ../packages/tko/docs/browser-support.md
 # - ../packages/tko/docs/docs.md
 # - ../packages/tko/docs/fn.md
 # - ../packages/tko/docs/installation.md
 # - ../packages/tko/docs/intro.md
 # - ../packages/tko/docs/json-data.md
 # - ../packages/tko/docs/links.md
 # - ../packages/tko/docs/plugins.md